### PR TITLE
Fix vagrant auto-mount of vmhgfs shared directories

### PR DESCRIPTION
**Pull request by segfly**
This fixes the issue I had with mitchellh/vagrant#6402

### CODE REVIEW

**Comment by kikitux** [comment]
Hello,

I think the best fix is on the template for the vagranfile

I have submitted this:

https://github.com/codekitchen/boot2docker-vagrant-box/pull/3

**Comment by segfly** [comment]
@codekitchen I agree with @kikitux PR #3 is probably better overall. I'm using atlas to build my own fork and there I had already revved to 1.8.2 there, but was unsure you wanted to update b2d.

I'll let you close this PR if you are going to merge #3.

**Comment by codekitchen** [comment]
Hey @segfly , I'm happy to merge that PR in. I'm a little surprised to even see this come up though -- this fork of https://github.com/dduportal/boot2docker-vagrant-box was only ever intended to be used internally  by my program https://github.com/codekitchen/dinghy on OS X using vmware fusion, and is now deprecated because dinghy doesn't use vagrant anymore. I was actually getting ready to delete the repo. What are you using it for?

**Comment by segfly** [comment]
@codekitchen At the time, you had the most up-to-date vagrant box for boot2docker (1.8.1). I was using it standalone from your other project because I wanted an easy way to run docker builds locally on my windows machine under vmware workstation.

As mentioned, I already forked this and made changes to run b2d 1.8.2 and build under atlas. If you don't want to maintain this any longer, I'll be happy to keep it alive under my fork. Just let me know.

**Comment by codekitchen** [comment]
Cool yeah -- you taking over a fork would be best, as I won't be maintaining it anymore. Thanks.

**Comment by segfly** [comment]
Works for me. I just pulled in the changes from #3  into my fork under a separate branch. So feel free to delete your repo. I'll rewrite the readme.md in my master branch and give you credit for the original codebase.

Thanks! :+1:

**Comment by segfly** [comment]
Oh, and if you delete this repo, you might also consider deleting the box from atlas.

**Comment by codekitchen** [comment]
Yeah... that's why I haven't deleted it yet, I know some people are still using old versions of dinghy that need the atlas boxes still. I'm waiting for them to upgrade.

**Pull request closed without merging**
